version: '3'
services:
  CN-0:
    hostname: CN-0
    image: klaytn-nohkwak-1.10.2
    ports:
      - '32323:32323'
      - '8551:8551'
      - '61001:61001'
    entrypoint:
      - /bin/sh
      - -c
      - |
        mkdir -p /klaytn
        echo '{"config":{"chainId":1000,"istanbulCompatibleBlock":0,"londonCompatibleBlock":0,"ethTxTypeCompatibleBlock":0,"magmaCompatibleBlock":0,"koreCompatibleBlock":0,"kip103CompatibleBlock":0,"kip103ContractAddress":"0x0000000000000000000000000000000000000000","istanbul":{"epoch":3600,"policy":0,"sub":22},"unitPrice":0,"deriveShaImpl":2,"governance":null},"timestamp":"0x64195de0","extraData":"0x0000000000000000000000000000000000000000000000000000000000000000f85ad5943573d550f1eaaa3cedc949dd8b33b7302bc78ce0b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0","governanceData":null,"blockScore":"0x1","alloc":{"3208ca99480f82bfe240ca6bc06110cd12bb6366":{"balance":"0x446c3b15f9926687d2c40534fdb564000000000000"}},"number":"0x0","gasUsed":"0x0","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000"}' > /klaytn/genesis.json
        echo '["kni://291f71eb09b8153f79c86d4380ca4576ba9c97c8342c93c0e65a1658867b2e11fec17a3cd0ad1d5bf8004e02e39f72826281b366c7f8679767a974bad2237153@172.16.239.10:32323?discport=0\u0026ntype=cn"]' > /klaytn/static-nodes.json
        kcn --datadir "/klaytn" init "/klaytn/genesis.json"
        echo "# docker-compose" >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'NETWORK=""' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'DATA_DIR="/klaytn"' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'LOG_DIR="$$DATA_DIR/log"' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'RPC_ENABLE=1' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'RPC_API="db,eth,klay,net,web3,miner,personal,txpool,debug,admin,istanbul,mainbridge,subbridge"' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'NETWORK_ID="203"' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'NO_DISCOVER=1' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'ADDITIONAL="$$ADDITIONAL --identity \"CN-0\""' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'ADDITIONAL="$$ADDITIONAL --nodekeyhex 56107981c4534e5bd20547692e6b9cfc626e51a637908e8e07a30c5f74820195"' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'REWARDBASE=0x3208ca99480f82bfe240ca6bc06110cd12bb6366' >> /klaytn-docker-pkg/conf/kcnd.conf
        echo 'ADDITIONAL="$$ADDITIONAL --debug --metrics --prometheus"' >> /klaytn-docker-pkg/conf/kcnd.conf
        /klaytn-docker-pkg/bin/kcnd start
        sleep 1
        ken attach --exec "personal.importRawKey('', '')" http://localhost:8551
        ken attach --exec "personal.unlockAccount('0x3208ca99480f82bfe240ca6bc06110cd12bb6366', '', 999999999)" http://localhost:8551
        tail -F klaytn/log/kcnd.out
    networks:
      app_net:
        ipv4_address: 172.16.239.10
    restart: "no"
  prometheus:
    hostname: prometheus
    image: prom/prometheus:v2.3.2
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      app_net:
        ipv4_address: 172.16.239.9
    restart: "no"

  grafana:
    hostname: grafana
    image: grafana/grafana:5.2.2
    ports:
      - 3000:3000
    networks:
      app_net:
        ipv4_address: 172.16.239.8
    restart: "no"

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24